### ISSUE TITLE
SingleKey and missing "code" in query dict

### ISSUE THREAD

**Issue by vanrein** [hcpy2-0/hcpy#110]
Great project.  I'd love to connect an ESP32 to the knobs from my old gas stove and use it to control the temperature/boost settings of my induction stove.

I am experiencing a problem when I login to my account,

```
    code = query.get("code")[0]
           ~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

The `query` dictionary has keys `'token'` and `'redirect_uri'` and I suspect this would happen to others as well.  But it is not reported, which makes me unsure.

So, **is hcpy lagging behind the site?** or do others fix this somehow?

**Comment by Meatballs1** [comment]
I was using hclogin the other day without issue. What region are you in, think there was similar if not EU or USA servers

**Comment by vanrein** [comment]
Thanks; I am in the EU.  FWIW, I did not use the App to registser and I do not have a device yet; but it seems to occur during login.

**Comment by Hypfer** [comment]
So what you did is create a SingleKey ID via the Web and that's it. At least I think you did.
You didn't explicitly say it - just slightly hinting at it in a second comment, literally requiring some mind reading skills.

So I just tried doing the same and indeed I can observe the same behavior.

Is this a problem? No
This scenario can not happen if you actually have devices that could be used with hcpy, because to join those, that cloud account will also get the right provisioning or whatever so that it responds with a JWT for home connect.
I mean I can see why this issue exists. You probably wanted to make sure that hcpy works before committing to purchasing an expensive appliance.

Still, this is exactly the kind of frustrating time waster that eats away at the time developers would prefer to commit to actually developing things. The things you want them to do. Build software that work and all.

Generally speaking, it's better to take a step back, document what is happening, document any details (e.g. the ones that only suddenly appeared the second comment), think about it for some more and only after that open an issue.

This way, a lot of problems solve themselves right away not even requiring an issue.
And if they don't, the issues turn out much better, making it much more likely that there will be a helpful answer.

**Comment by Hypfer** [comment]
Addendum:
The URL the login script ends up at in this case is eu.services.home-connect.com/registration/client

![image](https://github.com/user-attachments/assets/05f8ba81-b62e-4a0d-8075-1a13734b5ad5)

looking like this in a browser:

![image](https://github.com/user-attachments/assets/10bd0271-6035-4d51-87ad-5e4367dd5f72)

**Comment by vanrein** [comment]
Apologies for making you read my mind... I was confused by the response.  But yes, I was trying hc-login.py with the device still in the mail.

To soften the trouble a bit: I have had the idea of adding a bit more documentation / feedback / hints to the tool.  I was expecting it to do something logical if I tried an unlogical but common thing.  I hope to send you a PR in due time.
