### ISSUE TITLE
Add mqtt lwt

### ISSUE THREAD

**Issue by bartsnijder** [hcpy2-0/hcpy#21]
Could a mqtt LWT be added such that the online state of the device can always be determined?
Thanks! 

(Sorry for submitting issues/CR without solutions, I've not yet contributed to github projects before and still need to figure out the flow)

**Comment by Meatballs1** [comment]
I've added a line to do a generic `Offline` to a /status topic but I don't know MQTT standards very well to know the expected comms. I think I can probably get it to fire `Online` on connect if that helps?

**Comment by pmagyar** [comment]
@bartsnijder  tomorrow i have planned to write a contribution guideline.
With this help, maybe your are interested to fix future issues.
If you can't find your way around, feel free to write in the issue where you're currently stuck and we'll help you.
But your testing and communicating the problem is very helpful in itself!

**Comment by bartsnijder** [comment]
You can use retain to make sure it is kept by the broker
When first time online:
client.publish(mqtt_topic + "/LWT",payload="Online", qos=0, retain=True)
When device poll fails:
client.publish(mqtt_topic + "/LWT",payload="Offline", qos=0, retain=True)

**Comment by Meatballs1** [comment]
The branch should now send Online/Offline to homeconnect/LWT topic.

There didn't appear to be any standard, tasmota sends it to LWT, home assistant sends it to status and is lowercase etc
